ViewModels/PermissionViewModel.cs
using Microsoft.AspNetCore.Identity;

namespace FirstWebApplication.ViewModels
{
    public class PermissionViewModel
    {
        public RoleManager<IdentityRole> RoleManager { get; set; }
        public string RoleId { get; set; }
        public IList<RoleClaimsViewModel> RoleClaims { get; set; }//Represents a list of RoleClaimsViewModel objects,
                                                                  //each representing a permission associated with the role.
    }
    //This class represents a view model for a single permission associated with a role.
    public class RoleClaimsViewModel
    {
        public string Type { get; set; }
        public string Value { get; set; }
        public bool Selected { get; set; }
    }
}

Controllers/Controllers/PermissionController.cs
using FirstWebApplication.Constants;
using FirstWebApplication.Helpers;
using FirstWebApplication.Models;
using FirstWebApplication.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FirstWebApplication.Controllers
{
    public class PermissionController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public PermissionController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        //This method is rendering the data for manage permission view.
        public async Task<ActionResult> Index(string Id)
        {
            //A new instance of PermissionViewModel is created to hold data for the view.
            var model = new PermissionViewModel();
            //A new empty list of RoleClaimsViewModel objects is created to hold all permissions.
            var allPermissions = new List<RoleClaimsViewModel>();

            // Permissions for the "Products" module are retrieved using the GeneratePermissionsForModule method from
            // the Permissions class. Each permission is converted into a RoleClaimsViewModel object and
            // added to the allPermissions list.
            var productsPermissions = Permissions<Products>.GeneratePermissionsForModule("Products")
                                           .Select(permission => new RoleClaimsViewModel { Value = permission })
                                           .ToList();
            allPermissions.AddRange(productsPermissions);

            // Retrieve permissions for the "Order" module

            var orderPermissions = Permissions<Orders>.GeneratePermissionsForModule("Orders")
                                               .Select(permission => new RoleClaimsViewModel {  Value = permission })
                                               .ToList();
            allPermissions.AddRange(orderPermissions);

            // Retrieve the role based on the provided role ID
            var role = await _roleManager.FindByIdAsync(Id);
            if (role == null)
            {
                // Handle the case where the role is not found
                ModelState.AddModelError("", $"Role with ID {Id} not found.");
                return View(model); // Or handle the error appropriately
            }
            //The RoleId property of the model is set
            model.RoleId = Id;
            

            // Claims associated with the retrieved role are retrieved 
            var claims = await _roleManager.GetClaimsAsync(role);
            //The values of these claims are extracted into a list.
            var roleClaimValues = claims.Select(a => a.Value).ToList();

            // The intersection of all permission values and role claim values is calculated to find
            // which permissions are authorized for the role.
            var authorizedClaims = allPermissions.Select(a => a.Value)
                                                 .Intersect(roleClaimValues)
                                                 .ToList();

            // For each permission in allPermissions, if the permission's value is found in the authorizedClaims list,
            // the Selected property of that permission in the model is set to true.
            foreach (var permission in allPermissions)
            {
                if (authorizedClaims.Any(aC => aC == permission.Value))
                {
                    permission.Selected = true;
                }
            }
            //Finally, the RoleClaims property of the model is set to the list of all permissions,
            //including their selection status.
            model.RoleClaims = allPermissions;
            model.RoleManager = _roleManager;   //passing roleManager to view to see the roleName
            return View(model);
        }

        //Once the Admin Maps new Permission to a selected user and click the Save Button,
        //the enabled permissions are added to the Role.
        public async Task<IActionResult> Update(PermissionViewModel model)
        {
            string Id = model.RoleId;
            var role = await _roleManager.FindByIdAsync(Id);
            var claims = await _roleManager.GetClaimsAsync(role); 
            foreach (var claim in claims)
            {
                await _roleManager.RemoveClaimAsync(role, claim);
            }
            var selectedClaims = model.RoleClaims.Where(a => a.Selected).ToList();
            foreach (var claim in selectedClaims)
            {
                await _roleManager.AddPermissionClaim(role, claim.Value); //AddPermissionClaim method is defined in ClaimsHelper
            }
            //return RedirectToAction("Index", new { roleId = model.RoleId });
            return RedirectToAction("Index", "Role");
        }
    }
}
//The index method returns a list of DTO models that contains the details on which Permissions
//are active for the corresponding UserRole.
//public async Task<ActionResult> Index(string Id)
//{
//A new instance of PermissionViewModel is created to hold data for the view.
//    var model = new PermissionViewModel();
//A new empty list of RoleClaimsViewModel objects is created to hold all permissions.
//    var allPermissions = new List<RoleClaimsViewModel>();
//    allPermissions.GetPermissions(typeof(Permissions.Products), Id);//all available permissions for policy=Permissions.Products
//    var role = await _roleManager.FindByIdAsync(Id);
//    model.RoleId = Id;

//    var claims = await _roleManager.GetClaimsAsync(role);//Claims associated with the retrieved role
//    var allClaimValues = allPermissions.Select(a => a.Value).ToList(); //'list' of all claims available
//    var roleClaimValues = claims.Select(a => a.Value).ToList(); //'list' of claims associated with the role

//    //The intersection of all permission values and role claim values is calculated to find which permissions are authorized for the role.
//    var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();

//    //For each permission in allPermissions, if the permission's value is found in the authorizedClaims list,
//    //the Selected property of that permission in the model is set to true.
//    foreach (var permission in allPermissions)
//    {
//        if (authorizedClaims.Any(a => a == permission.Value))
//        {
//            permission.Selected = true;
//        }
//    }
//    //Finally, the RoleClaims property of the model is set to the list of all permissions, including their selection status.
//    model.RoleClaims = allPermissions;
//    return View(model);
//}

Views/Permission/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model FirstWebApplication.ViewModels.PermissionViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    // Retrieve the role name using the roleId
    var roleName = await Model.RoleManager.FindByIdAsync(Model.RoleId);
    var roleNameValue = roleName?.Name; // Check for null before accessing the Name property
}

<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>ChocoLux</title>


    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
    <!--slick slider stylesheet -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick-theme.min.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet" />
    <!-- slick slider -->

    <link rel="stylesheet" href="css/slick-theme.css" />
    <!-- font awesome style -->
    <link href="css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="css/responsive.css" rel="stylesheet" />

</head>

<body>

    <h2>Manage Permissions for @roleNameValue </h2>
<br />
<div class="card">
    <div id="viewAll" class="card-body table-responsive">
        <form asp-controller="Permission" method="post" asp-action="Update" class="d-inline">
            <input asp-for="@Model.RoleId" type="hidden" />
            <table class="table table-striped" id="permissionTable">
                <thead>
                    <tr>
                        @* <th>
                            Type
                        </th> *@
                        <th>
                                <h2>Permission</h2>
                        </th>
                        <th>
                                <h2>Status</h2>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    
                    @for (int i = 0; i < Model.RoleClaims.Count(); i++)
                    {
                        <tr>
                            @* <td>
                                <input asp-for="@Model.RoleClaims[i].Type" type="hidden" />
                                @Model.RoleClaims[i].Type
                            </td> *@
                            <td>
                                <input asp-for="@Model.RoleClaims[i].Value" type="hidden" />
                                @Model.RoleClaims[i].Value
                            </td>
                            <td>
                                <div class="form-check m-1">
                                    <input asp-for="@Model.RoleClaims[i].Selected" class="form-check-input" />
                                </div>
                            </td>
                        </tr>
                            // Add a condition to insert empty rows after every fourth row
                            @if ((i + 1) % 4 == 0)
                            {
                                <tr style="height: 20px;"></tr> <!-- Empty row -->
                                <tr style="height: 20px;"></tr> <!-- Empty row -->
                            }
                    }
                </tbody>
            </table>
            <div class="col-sm-12" style="padding: 20px 20px 0px 0px">
                <button type="submit" id="save" class="btn btn-success">
                    <i class="fa fa-check"></i>
                    Save
                </button>
                <a asp-action="Index" asp-controller="Role"
                   class="btn btn-primary" style="width:auto">Cancel</a>
            </div>
        </form>
    </div>
</div>
    <!-- jQuery -->
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <!-- bootstrap js -->
    <script src="~/js/bootstrap.js"></script>
    <!-- slick slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick.min.js"></script>
    <!-- custom js -->
    <script src="~/js/custom.js"></script>
    <!-- Custom Styles -->
    <style>
        .btn-brown {
            background-color: #8B4513; /* Brown color */
            border-color: #8B4513; /* Brown color for border */
        }

            .btn-brown:hover {
                background-color: #654321; /* Darker brown on hover */
                border-color: #654321; /* Darker brown for border on hover */
            }

    </style>
</body>
</html>